language: python
python:
  - "2.7"

#Set virtual env with system-site-packages to true
virtualenv:
  system_site_packages: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install: 
  - sudo apt-get install -qq python-scipy python-pip
  - sudo apt-get install -qq python-matplotlib