sudo: false

os:
  - osx
  - linux

#language: python

#addons:
#  apt:
#    packages:
#      - gfortran
#      - libatlas-dev
#      - libatlas-base-dev
#      - liblapack-dev

cache:
  directories:
     - $HOME/miniconda/

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=3.4

before_install:
  - export CONDA_CACHED=1
  - if [ ! -d $HOME/miniconda/bin ]; then
      export CONDA_CACHED=0;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export OS=Linux;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export OS=MacOSX;
      else
        echo "OS not supported yet";
        exit 1;
      fi;
      if [[ $PYTHON_VERSION == "2.7" ]]; then
        export MINICONDA=Miniconda;
      elif [[ $PYTHON_VERSION == 3* ]]; then
        export MINICONDA=Miniconda3;
      else
        echo "Could not find python version";
        exit 1;
      fi;
      wget http://repo.continuum.io/miniconda/$MINICONDA-latest-$OS-x86_64.sh -O miniconda.sh;
      chmod +x miniconda.sh;
      ./miniconda.sh -b -p $HOME/miniconda;
    fi;
  - echo $PATH
  - ls $HOME/miniconda/bin
  - alias conda=$HOME/miniconda/bin/conda
#  - conda update --yes conda
  
install:
  - echo $CONDA_CACHED
  - if [[ $CONDA_CACHED == 0 ]]; then
      conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six;
    else
      conda upgrade python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six;
    fi;
  - pip install --upgrade .

before_script:
  - cd $HOME
  - mkdir empty
  - cd empty
   
script:
  - nosetests GPy.testing
