sudo: false

os:
  - linux
  - osx

#language: python

#addons:
#  apt:
#    packages:
#      - gfortran
#      - libatlas-dev
#      - libatlas-base-dev
#      - liblapack-dev

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=3.4

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      exit 1;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - echo $PATH
#  - conda update --yes conda
  
install:
  - export PATH=/home/travis/miniconda/bin:$PATH
  - echo $PATH
  - conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six
  - pip install .

before_script:
  - cd $HOME
  - mkdir empty
  - cd empty
   
script:
  - nosetests GPy.testing

cache:
  directories:
    - $HOME/.cache/pip
