sudo: false

os:
  - osx
  - linux

#language: python

#addons:
#  apt:
#    packages:
#      - gfortran
#      - libatlas-dev
#      - libatlas-base-dev
#      - liblapack-dev

cache:
  directories:
     - $HOME/download/
     - $HOME/install/

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=3.4

before_install:
  - export CONDA_CACHED=1
  - if [ ! -f download/$MINICONDA-latest-$OS-x86_64.sh ]; then
      export CONDA_CACHED=0;
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export OS=Linux;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export OS=MacOSX;
      else
        echo "OS not supported yet";
        exit 1;
      fi;
      if [[ $PYTHON_VERSION == "2.7" ]]; then
        export MINICONDA=Miniconda;
      elif [[ $PYTHON_VERSION == 3* ]]; then
        export MINICONDA=Miniconda3;
      else
        echo "Could not find python version";
        exit 1;
      fi;
      wget http://repo.continuum.io/miniconda/$MINICONDA-latest-$OS-x86_64.sh -O download/$MINICONDA-latest-$OS-x86_64.sh;
      chmod +x download/$MINICONDA-latest-$OS-x86_64.sh;
      ./download/$MINICONDA-latest-$OS-x86_64.sh -b -p $HOME/install/$MINICONDA-latest-$OS-x86_64/;
    fi;
  - export PATH="$HOME/install/$MINICONDA-latest-$OS-x86_64/bin:$PATH"
  
install:
  - conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six;
  - python -V
  - pip install --upgrade .

before_script:
  - cd $HOME
  - mkdir empty
  - cd empty
   
script:
  - nosetests GPy.testing
