language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - sudo apt-get install python-scipy
  - pip install sphinx
  - pip install . --use-mirrors
# command to run tests, e.g. python setup.py test
script: 
  - nosetests --with-xcoverage --with-xunit --cover-package=GPy --cover-erase GPy/testing
